default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: [--line-length=99, --target-version=py38]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        args: [--show-error-codes, --ignore-missing-imports, --explicit-package-bases]
        # By using `language: system` we run this hook in the local
        # environment instead of a pre-commit isolated one.
        # This is needed to ensure mypy correctly parses the project.
        # See https://github.com/pre-commit/pre-commit/issues/730 for details.
        language: system
